//@version = 6
indicator("j 7" , "zz" , true)

dmn = 5
var lst_pvt = ""

var float pst_top_prc = na , var int pst_top_bar = na
var float lst_top_prc = na , var int lst_top_bar = na

var float pst_bot_prc = na , var int pst_bot_bar = na
var float lst_bot_prc = na , var int lst_bot_bar = na

top = ta.pivothigh(dmn , dmn)
bot = ta.pivotlow (dmn , dmn)


var line inc = na , var line dec = na ,



if lst_pvt == "top"
    if high >= lst_top_prc      
        if bool(bot)
            // label.new(bar_index+5,high , lst_pvt)
            if bar_index >= (lst_top_bar+5)
                lst_pvt := "bot"
                pst_bot_prc := lst_bot_prc , pst_bot_bar := lst_bot_bar
                lst_bot_prc := low [dmn]   , lst_bot_bar := bar_index[dmn]
                dec := line.new(lst_top_bar , lst_top_prc , lst_bot_bar , lst_bot_prc , color = color.orange)
            else
                lst_top_prc := high , lst_top_bar := bar_index
                inc.set_x2(lst_top_bar) , inc.set_y2(lst_top_prc)
        else
            lst_top_prc := high , lst_top_bar := bar_index
            inc.set_x2(lst_top_bar) , inc.set_y2(lst_top_prc)
    else
        if (bool(bot) and bool(top))
            if (open-low) > (high-open)
                lst_top_prc := high[5] , lst_top_bar := bar_index[5]
                lst_pvt := "bot"
                pst_bot_prc := lst_bot_prc , pst_bot_bar := lst_bot_bar
                lst_bot_prc := low [dmn]   , lst_bot_bar := bar_index[dmn]
                dec := line.new(lst_top_bar , lst_top_prc , lst_bot_bar , lst_bot_prc , color = color.orange)
            else
                lst_pvt := "bot-top"
                pst_bot_prc := lst_bot_prc , pst_bot_bar := lst_bot_bar
                lst_bot_prc := low [dmn]   , lst_bot_bar := bar_index[dmn]
                pst_top_prc := lst_top_prc , pst_top_bar := lst_top_bar
                lst_top_prc := high[dmn]   , lst_top_bar := bar_index[dmn]
                dec := line.new(lst_top_bar , lst_top_prc , lst_bot_bar , lst_bot_prc , color = color.orange)
                inc := line.new(lst_bot_bar , lst_bot_prc , lst_top_bar , lst_top_prc , color = color.blue)
        else if bool(bot)
            lst_pvt := "bot"
            pst_bot_prc := lst_bot_prc , pst_bot_bar := lst_bot_bar
            lst_bot_prc := low [dmn]   , lst_bot_bar := bar_index[dmn]
            dec := line.new(lst_top_bar , lst_top_prc , lst_bot_bar , lst_bot_prc , color = color.orange)



if lst_pvt == "bot"
    if low  <= lst_bot_prc      
        if bool(top)
            lst_pvt := "top"
            pst_top_prc := lst_top_prc , pst_top_bar := lst_top_bar
            lst_top_prc := high[dmn]   , lst_top_bar := bar_index[dmn]
            inc := line.new(lst_bot_bar , lst_bot_prc , lst_top_bar , lst_top_prc , color = color.blue)
        else
            lst_bot_prc := low  , lst_bot_bar := bar_index
            dec.set_x2(lst_bot_bar) , dec.set_y2(lst_bot_prc)
    else
        if (bool(top) and bool(bot))
            if (open-low) < (high-open)
                lst_bot_prc := low [5] , lst_bot_bar := bar_index[5]
                lst_pvt := "top"
                pst_top_prc := lst_top_prc , pst_top_bar := lst_top_bar
                lst_top_prc := high[dmn]   , lst_top_bar := bar_index[dmn]
                inc := line.new(lst_bot_bar , lst_bot_prc , lst_top_bar , lst_top_prc , color = color.blue)
            else
                lst_pvt := "top-bot"
                pst_top_prc := lst_top_prc , pst_top_bar := lst_top_bar
                lst_top_prc := high[dmn]   , lst_top_bar := bar_index[dmn]
                pst_bot_prc := lst_bot_prc , pst_bot_bar := lst_bot_bar
                lst_bot_prc := low [dmn]   , lst_bot_bar := bar_index[dmn]
                inc := line.new(lst_bot_bar , lst_bot_prc , lst_top_bar , lst_top_prc , color = color.blue)
                dec := line.new(lst_top_bar , lst_top_prc , lst_bot_bar , lst_bot_prc , color = color.orange)
        else if bool(top)
            lst_pvt := "top"
            pst_top_prc := lst_top_prc , pst_top_bar := lst_top_bar
            lst_top_prc := high[dmn]   , lst_top_bar := bar_index[dmn]
            inc := line.new(lst_bot_bar , lst_bot_prc , lst_top_bar , lst_top_prc , color = color.blue)


if lst_pvt == ""
    if (bool(top) and bool(bot))
        if (open-low) < (high-open)
            lst_pvt := "bot-top"
            pst_bot_prc := lst_bot_prc , pst_bot_bar := lst_bot_bar
            lst_bot_prc := low [dmn]   , lst_bot_bar := bar_index[dmn]
            pst_top_prc := lst_top_prc , pst_top_bar := lst_top_bar
            lst_top_prc := high[dmn]   , lst_top_bar := bar_index[dmn]
            dec := line.new(lst_top_bar , lst_top_prc , lst_bot_bar , lst_bot_prc , color = color.orange)
            inc := line.new(lst_bot_bar , lst_bot_prc , lst_top_bar , lst_top_prc , color = color.blue)
        else
            lst_pvt := "top-bot"
            pst_top_prc := lst_top_prc , pst_top_bar := lst_top_bar
            lst_top_prc := high[dmn]   , lst_top_bar := bar_index[dmn]
            pst_bot_prc := lst_bot_prc , pst_bot_bar := lst_bot_bar
            lst_bot_prc := low [dmn]   , lst_bot_bar := bar_index[dmn]
            inc := line.new(lst_bot_bar , lst_bot_prc , lst_top_bar , lst_top_prc , color = color.blue)
            dec := line.new(lst_top_bar , lst_top_prc , lst_bot_bar , lst_bot_prc , color = color.orange)
    else if bool(top)
        lst_pvt := "top"
        pst_top_prc := lst_top_prc , pst_top_bar := lst_top_bar
        lst_top_prc := high[dmn]   , lst_top_bar := bar_index[dmn]
        // inc := line.new(lst_bot_bar , lst_bot_prc , lst_top_bar , lst_top_prc , color = color.blue)
    else if bool(bot)
        lst_pvt := "bot"
        pst_bot_prc := lst_bot_prc , pst_bot_bar := lst_bot_bar
        lst_bot_prc := low [dmn]   , lst_bot_bar := bar_index[dmn]
        // dec := line.new(lst_top_bar , lst_top_prc , lst_bot_bar , lst_bot_prc , color = color.orange)

